import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const colleges = [
  {
    name: "Indian Institute of Technology Bombay",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    fees: 220000,
    rating: 4.8,
    placementsPercentage: 98,
    description:
      "IIT Bombay is one of India's premier engineering institutes, known for cutting-edge research and world-class faculty. Established in 1958, it offers undergraduate, postgraduate, and doctoral programs across various disciplines.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=400",
    website: "https://www.iitb.ac.in",
    phone: "+91-22-2572-2545",
    email: "info@iitb.ac.in",
    established: 1958,
    totalStudents: 10000,
    accreditation: "NAAC A++",
    type: "Government",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 220000, seats: 120 },
      { name: "B.Tech Electrical Engineering", duration: "4 years", fees: 220000, seats: 100 },
      { name: "M.Tech AI & ML", duration: "2 years", fees: 200000, seats: 60 },
      { name: "MBA Technology Management", duration: "2 years", fees: 300000, seats: 40 },
    ],
    reviews: [
      { rating: 5, comment: "World-class faculty and research opportunities. Best decision of my life!", author: "Rahul Sharma", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.5, comment: "Excellent placements and campus life. Infrastructure is top-notch.", author: "Priya Patel", batch: "2021", course: "B.Tech EE" },
      { rating: 5, comment: "The alumni network is incredible. Doors open everywhere with an IIT degree.", author: "Amit Kumar", batch: "2020", course: "M.Tech AI" },
    ],
  },
  {
    name: "Indian Institute of Technology Delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    fees: 210000,
    rating: 4.7,
    placementsPercentage: 97,
    description:
      "IIT Delhi is a leading technical university in India's capital, offering programs in engineering, science, and management. Known for innovation, research, and strong industry connections.",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=400",
    website: "https://www.iitd.ac.in",
    phone: "+91-11-2659-1000",
    email: "info@iitd.ac.in",
    established: 1961,
    totalStudents: 8500,
    accreditation: "NAAC A++",
    type: "Government",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 210000, seats: 110 },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 210000, seats: 90 },
      { name: "M.Tech Data Science", duration: "2 years", fees: 190000, seats: 50 },
    ],
    reviews: [
      { rating: 5, comment: "Delhi location gives amazing internship opportunities. Great college!", author: "Sneha Gupta", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.5, comment: "Research facilities are excellent. Professors are very supportive.", author: "Vikas Sharma", batch: "2021", course: "M.Tech DS" },
    ],
  },
  {
    name: "BITS Pilani",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    fees: 580000,
    rating: 4.6,
    placementsPercentage: 95,
    description:
      "BITS Pilani is a premier deemed university known for its Practice School program that places students in top companies for real-world experience. One of the most innovative institutions in India.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400",
    website: "https://www.bits-pilani.ac.in",
    phone: "+91-1596-242-192",
    email: "admissions@bits-pilani.ac.in",
    established: 1964,
    totalStudents: 12000,
    accreditation: "NAAC A",
    type: "Deemed",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 580000, seats: 150 },
      { name: "B.E. Electronics & Communication", duration: "4 years", fees: 580000, seats: 120 },
      { name: "M.Sc. Mathematics", duration: "2 years", fees: 400000, seats: 60 },
      { name: "MBA", duration: "2 years", fees: 650000, seats: 80 },
    ],
    reviews: [
      { rating: 4.5, comment: "Practice School is a game changer. Got placed in Google during PS!", author: "Kartik Mehta", batch: "2022", course: "B.E. CSE" },
      { rating: 5, comment: "Liberal academic system lets you explore multiple fields. Loved it!", author: "Nisha Jain", batch: "2021", course: "B.E. ECE" },
    ],
  },
  {
    name: "National Institute of Technology Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    fees: 180000,
    rating: 4.5,
    placementsPercentage: 93,
    description:
      "NIT Trichy is consistently ranked among the top NITs in India. Known for its excellent engineering programs, strong alumni network, and impressive placement record across top companies.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400",
    website: "https://www.nitt.edu",
    phone: "+91-431-250-3000",
    email: "info@nitt.edu",
    established: 1964,
    totalStudents: 7000,
    accreditation: "NAAC A++",
    type: "Government",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 180000, seats: 80 },
      { name: "B.Tech Civil Engineering", duration: "4 years", fees: 180000, seats: 70 },
      { name: "M.Tech Software Engineering", duration: "2 years", fees: 160000, seats: 30 },
    ],
    reviews: [
      { rating: 4.5, comment: "NIT Trichy placements are excellent. Most students placed in top MNCs.", author: "Arun Krishnan", batch: "2022", course: "B.Tech CSE" },
      { rating: 4, comment: "Excellent environment for technical growth. Fest culture is vibrant too!", author: "Divya Menon", batch: "2021", course: "B.Tech Civil" },
    ],
  },
  {
    name: "Vellore Institute of Technology",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    fees: 400000,
    rating: 4.2,
    placementsPercentage: 90,
    description:
      "VIT University is one of India's largest private engineering institutions offering more than 50 UG and PG programs. Known for its international collaborations and modern infrastructure.",
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400",
    website: "https://www.vit.ac.in",
    phone: "+91-416-220-2125",
    email: "ugadmission@vit.ac.in",
    established: 1984,
    totalStudents: 50000,
    accreditation: "NAAC A++",
    type: "Deemed",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 400000, seats: 600 },
      { name: "B.Tech AI & Robotics", duration: "4 years", fees: 430000, seats: 120 },
      { name: "M.Tech Software Engineering", duration: "2 years", fees: 350000, seats: 100 },
      { name: "MBA Business Analytics", duration: "2 years", fees: 500000, seats: 80 },
    ],
    reviews: [
      { rating: 4, comment: "Great campus, amazing hostels, and solid placements. VIT never disappoints.", author: "Rohit Nair", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.5, comment: "International exposure is great. Had exchange program to Germany!", author: "Simran Kaur", batch: "2021", course: "B.Tech AI" },
    ],
  },
  {
    name: "Manipal Institute of Technology",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    fees: 450000,
    rating: 4.1,
    placementsPercentage: 88,
    description:
      "MIT Manipal is a premier private engineering college under Manipal Academy of Higher Education. Offers excellent technical education with strong industry partnerships and international tie-ups.",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=400",
    website: "https://manipal.edu/mit.html",
    phone: "+91-820-292-1000",
    email: "admissions@manipal.edu",
    established: 1957,
    totalStudents: 20000,
    accreditation: "NAAC A++",
    type: "Deemed",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 450000, seats: 300 },
      { name: "B.Tech Mechatronics", duration: "4 years", fees: 460000, seats: 80 },
      { name: "M.Tech Data Science", duration: "2 years", fees: 380000, seats: 60 },
    ],
    reviews: [
      { rating: 4, comment: "Manipal has a great campus culture and excellent hostel facilities.", author: "Aditya Rao", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.2, comment: "Placements are decent. Companies like Infosys, TCS, Wipro visit regularly.", author: "Pooja Shetty", batch: "2021", course: "B.Tech Mech" },
    ],
  },
  {
    name: "SRM Institute of Science & Technology",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    fees: 350000,
    rating: 4.0,
    placementsPercentage: 87,
    description:
      "SRM is one of India's top-ranked universities offering diverse programs in engineering, medicine, and management. Known for research innovation and strong corporate connections.",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=400",
    website: "https://www.srmist.edu.in",
    phone: "+91-44-2745-5510",
    email: "admissions@srmist.edu.in",
    established: 1985,
    totalStudents: 52000,
    accreditation: "NAAC A++",
    type: "Deemed",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 350000, seats: 800 },
      { name: "B.Tech Biomedical Engineering", duration: "4 years", fees: 380000, seats: 60 },
      { name: "M.Tech Cloud Computing", duration: "2 years", fees: 300000, seats: 80 },
    ],
    reviews: [
      { rating: 4, comment: "SRM offers great industry connections. Placement rate is impressive.", author: "Kiran Bose", batch: "2022", course: "B.Tech CSE" },
      { rating: 3.8, comment: "Good college but fees are a bit high. Labs and infrastructure are excellent.", author: "Meena Pillai", batch: "2021", course: "B.Tech Biomedical" },
    ],
  },
  {
    name: "Amity University",
    location: "Noida, Uttar Pradesh",
    city: "Noida",
    state: "Uttar Pradesh",
    fees: 320000,
    rating: 3.9,
    placementsPercentage: 85,
    description:
      "Amity University is one of India's largest private universities with campuses across the country. It offers programs in engineering, law, media, business, and many more disciplines.",
    imageUrl: "https://images.unsplash.com/photo-1527576539890-dfa815648363?w=400",
    website: "https://www.amity.edu",
    phone: "+91-120-439-2000",
    email: "info@amity.edu",
    established: 2005,
    totalStudents: 150000,
    accreditation: "NAAC A+",
    type: "Private",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 320000, seats: 400 },
      { name: "BBA", duration: "3 years", fees: 250000, seats: 300 },
      { name: "MBA", duration: "2 years", fees: 450000, seats: 200 },
      { name: "B.Sc Biotechnology", duration: "3 years", fees: 280000, seats: 100 },
    ],
    reviews: [
      { rating: 4, comment: "Great infrastructure and diverse student community from across the globe.", author: "Anjali Verma", batch: "2022", course: "B.Tech CSE" },
      { rating: 3.8, comment: "College provides good exposure. MNC placement drive is organized well.", author: "Saurabh Mishra", batch: "2021", course: "MBA" },
    ],
  },
  {
    name: "Chandigarh University",
    location: "Chandigarh, Punjab",
    city: "Chandigarh",
    state: "Punjab",
    fees: 250000,
    rating: 4.1,
    placementsPercentage: 91,
    description:
      "Chandigarh University is a NAAC A+ accredited institution offering 109+ programs. Known for its exceptional placement record and vibrant campus life.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=400",
    website: "https://www.cuchd.in",
    phone: "+91-160-302-3453",
    email: "admissions@cumail.in",
    established: 2012,
    totalStudents: 30000,
    accreditation: "NAAC A+",
    type: "Private",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 250000, seats: 500 },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 240000, seats: 200 },
      { name: "MBA", duration: "2 years", fees: 350000, seats: 150 },
    ],
    reviews: [
      { rating: 4, comment: "Best placement record in North India. Got placed in Amazon with 24 LPA!", author: "Harpreet Singh", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.2, comment: "The faculty is extremely helpful and industry-oriented curriculum is great.", author: "Gurpreet Kaur", batch: "2021", course: "MBA" },
    ],
  },
  {
    name: "Lovely Professional University",
    location: "Phagwara, Punjab",
    city: "Phagwara",
    state: "Punjab",
    fees: 200000,
    rating: 3.8,
    placementsPercentage: 82,
    description:
      "LPU is one of India's largest single-campus universities, offering 200+ programs. Known for its diverse student community and practical learning approach.",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=400",
    website: "https://www.lpu.in",
    phone: "+91-1824-517-000",
    email: "admissions@lpu.co.in",
    established: 2005,
    totalStudents: 30000,
    accreditation: "NAAC A++",
    type: "Private",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 200000, seats: 700 },
      { name: "B.Des Fashion Design", duration: "4 years", fees: 220000, seats: 100 },
      { name: "BCA", duration: "3 years", fees: 160000, seats: 300 },
    ],
    reviews: [
      { rating: 3.8, comment: "Large campus with all facilities. Placement drive is good with 500+ companies.", author: "Mandeep Singh", batch: "2022", course: "B.Tech CSE" },
      { rating: 3.9, comment: "The practical exposure through industry projects is excellent at LPU.", author: "Shivani Rani", batch: "2021", course: "B.Des" },
    ],
  },
  {
    name: "Delhi Technological University",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    fees: 175000,
    rating: 4.3,
    placementsPercentage: 92,
    description:
      "DTU (formerly DCE) is one of Delhi's premier engineering universities. Known for cutting-edge research, innovative programs, and strong placement record in top tech companies.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400",
    website: "https://dtu.ac.in",
    phone: "+91-11-2787-1045",
    email: "info@dtu.ac.in",
    established: 1941,
    totalStudents: 10000,
    accreditation: "NAAC A",
    type: "Government",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 175000, seats: 90 },
      { name: "B.Tech Electronics", duration: "4 years", fees: 175000, seats: 80 },
      { name: "M.Tech Software Engineering", duration: "2 years", fees: 150000, seats: 40 },
    ],
    reviews: [
      { rating: 4.5, comment: "DTU's placement record is remarkable. Got placed in Microsoft at 32 LPA!", author: "Nikhil Arora", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.2, comment: "Great college with affordable fees and excellent faculty. Proud DTU alum!", author: "Tanvi Saxena", batch: "2021", course: "B.Tech Electronics" },
    ],
  },
  {
    name: "PSG College of Technology",
    location: "Coimbatore, Tamil Nadu",
    city: "Coimbatore",
    state: "Tamil Nadu",
    fees: 150000,
    rating: 4.2,
    placementsPercentage: 89,
    description:
      "PSG College of Technology is one of the oldest and most prestigious engineering colleges in South India, known for industry-relevant education and excellent alumni network.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400",
    website: "https://www.psgtech.edu",
    phone: "+91-422-257-2177",
    email: "principal@psgtech.edu",
    established: 1951,
    totalStudents: 8000,
    accreditation: "NAAC A++",
    type: "Private",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 150000, seats: 120 },
      { name: "B.E. Mechanical Engineering", duration: "4 years", fees: 140000, seats: 100 },
      { name: "M.E. Embedded Systems", duration: "2 years", fees: 130000, seats: 30 },
    ],
    reviews: [
      { rating: 4.2, comment: "PSG has an amazing legacy. Industry connections are strong and placements are great.", author: "Suresh Kumar", batch: "2022", course: "B.E. CSE" },
      { rating: 4.3, comment: "The faculty here are industry veterans. Learning is very practical and hands-on.", author: "Lavanya Ravi", batch: "2021", course: "B.E. Mech" },
    ],
  },
  {
    name: "Ramaiah Institute of Technology",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    fees: 220000,
    rating: 4.1,
    placementsPercentage: 88,
    description:
      "M.S. Ramaiah Institute of Technology is a well-known private engineering college in Bangalore, offering high-quality technical education with strong industry partnerships in the IT hub.",
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400",
    website: "https://www.msrit.edu",
    phone: "+91-80-2360-0822",
    email: "principal@msrit.edu",
    established: 1962,
    totalStudents: 6500,
    accreditation: "NAAC A",
    type: "Private",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 220000, seats: 180 },
      { name: "B.E. Information Science", duration: "4 years", fees: 210000, seats: 120 },
      { name: "M.Tech VLSI Design", duration: "2 years", fees: 190000, seats: 25 },
    ],
    reviews: [
      { rating: 4.1, comment: "Being in Bangalore, we get internship opportunities in top tech companies.", author: "Ravi Shankar", batch: "2022", course: "B.E. CSE" },
      { rating: 4.0, comment: "Ramaiah has excellent labs and a very supportive alumni network.", author: "Deepa Krishnaswamy", batch: "2021", course: "B.E. IS" },
    ],
  },
  {
    name: "PES University",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    fees: 400000,
    rating: 4.2,
    placementsPercentage: 91,
    description:
      "PES University is a top-ranked private university in Bangalore known for its research culture, industry-aligned curriculum, and exceptional placements in leading tech companies.",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=400",
    website: "https://pes.edu",
    phone: "+91-80-2672-1983",
    email: "admission@pes.edu",
    established: 1972,
    totalStudents: 12000,
    accreditation: "NAAC A+",
    type: "Private",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 400000, seats: 300 },
      { name: "B.Tech AI & Machine Learning", duration: "4 years", fees: 430000, seats: 120 },
      { name: "M.Tech Data Science", duration: "2 years", fees: 350000, seats: 60 },
    ],
    reviews: [
      { rating: 4.3, comment: "PES is where I got my dream placement at Google. Excellent college!", author: "Ananya Subramanian", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.1, comment: "Great faculty, great campus, and amazing placement support team.", author: "Varun Gowda", batch: "2021", course: "B.Tech AI" },
    ],
  },
  {
    name: "Thapar Institute of Engineering",
    location: "Patiala, Punjab",
    city: "Patiala",
    state: "Punjab",
    fees: 350000,
    rating: 4.2,
    placementsPercentage: 90,
    description:
      "Thapar Institute is a well-regarded deemed university known for its industry-ready curriculum, strong alumni base, and excellent placements in top MNCs and tech startups.",
    imageUrl: "https://images.unsplash.com/photo-1527576539890-dfa815648363?w=400",
    website: "https://www.thapar.edu",
    phone: "+91-175-239-3021",
    email: "admissions@thapar.edu",
    established: 1956,
    totalStudents: 15000,
    accreditation: "NAAC A",
    type: "Deemed",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 350000, seats: 200 },
      { name: "B.E. Electronics", duration: "4 years", fees: 340000, seats: 150 },
      { name: "M.E. Software Engineering", duration: "2 years", fees: 290000, seats: 50 },
    ],
    reviews: [
      { rating: 4.3, comment: "Thapar provides excellent coding culture. ACM and Google DSC chapters are active.", author: "Abhishek Gupta", batch: "2022", course: "B.E. CSE" },
      { rating: 4.1, comment: "The research opportunities here are amazing. Published 2 papers in undergrad!", author: "Navneet Kaur", batch: "2021", course: "B.E. Electronics" },
    ],
  },
  {
    name: "UPES Dehradun",
    location: "Dehradun, Uttarakhand",
    city: "Dehradun",
    state: "Uttarakhand",
    fees: 300000,
    rating: 3.9,
    placementsPercentage: 84,
    description:
      "UPES is a specialized university known for its programs in energy, engineering, and management. Offers unique specializations related to petroleum, power, and emerging technologies.",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=400",
    website: "https://www.upes.ac.in",
    phone: "+91-1800-102-8737",
    email: "admissions@upes.ac.in",
    established: 2003,
    totalStudents: 12000,
    accreditation: "NAAC A",
    type: "Private",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 300000, seats: 250 },
      { name: "B.Tech Oil & Gas Engineering", duration: "4 years", fees: 320000, seats: 60 },
      { name: "MBA Energy Management", duration: "2 years", fees: 480000, seats: 80 },
    ],
    reviews: [
      { rating: 3.9, comment: "Unique specializations not found elsewhere. Great for energy sector careers.", author: "Prakash Dobhal", batch: "2022", course: "B.Tech Oil & Gas" },
      { rating: 4.0, comment: "Beautiful campus in the hills. Academic support team is very helpful.", author: "Rishita Sharma", batch: "2021", course: "B.Tech CSE" },
    ],
  },
  {
    name: "KIIT University",
    location: "Bhubaneswar, Odisha",
    city: "Bhubaneswar",
    state: "Odisha",
    fees: 340000,
    rating: 4.0,
    placementsPercentage: 86,
    description:
      "KIIT is a deemed university in Bhubaneswar offering programs across engineering, management, law, and social sciences. Known for its beautiful campus and strong tech focus.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=400",
    website: "https://kiit.ac.in",
    phone: "+91-674-272-7787",
    email: "helpdesk@kiit.ac.in",
    established: 1992,
    totalStudents: 25000,
    accreditation: "NAAC A++",
    type: "Deemed",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 340000, seats: 400 },
      { name: "B.Tech Biotechnology", duration: "4 years", fees: 360000, seats: 80 },
      { name: "MBA", duration: "2 years", fees: 500000, seats: 120 },
    ],
    reviews: [
      { rating: 4.0, comment: "KIIT has grown rapidly. Campus is beautiful and placements have improved significantly.", author: "Subhashis Panda", batch: "2022", course: "B.Tech CSE" },
      { rating: 3.9, comment: "Great hostel life and campus facilities. Tech culture is strong here.", author: "Preethi Das", batch: "2021", course: "B.Tech Bio" },
    ],
  },
  {
    name: "Jadavpur University",
    location: "Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    fees: 50000,
    rating: 4.4,
    placementsPercentage: 91,
    description:
      "Jadavpur University is one of India's premier government universities known for its strong research tradition, excellent faculty, and very affordable government fees.",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=400",
    website: "https://www.jaduniv.edu.in",
    phone: "+91-33-2457-2057",
    email: "vcju@jadavpur.ac.in",
    established: 1955,
    totalStudents: 8000,
    accreditation: "NAAC A++",
    type: "Government",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 50000, seats: 60 },
      { name: "B.E. Electrical Engineering", duration: "4 years", fees: 45000, seats: 55 },
      { name: "M.E. Software Engineering", duration: "2 years", fees: 40000, seats: 25 },
    ],
    reviews: [
      { rating: 4.5, comment: "Best value for money engineering college in India! Fees are minimal, quality is top-notch.", author: "Debashis Ghosh", batch: "2022", course: "B.E. CSE" },
      { rating: 4.3, comment: "Strong academics and amazing research culture. Alumni base is incredible.", author: "Suchismita Roy", batch: "2021", course: "B.E. EE" },
    ],
  },
  {
    name: "Anna University",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    fees: 65000,
    rating: 4.3,
    placementsPercentage: 90,
    description:
      "Anna University is a technical university in Tamil Nadu affiliating hundreds of colleges across the state. The main campus in Chennai is known for research and excellent placements.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400",
    website: "https://www.annauniv.edu",
    phone: "+91-44-2235-9355",
    email: "registrar@annauniv.edu",
    established: 1978,
    totalStudents: 15000,
    accreditation: "NAAC A++",
    type: "Government",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 65000, seats: 100 },
      { name: "B.E. Electronics & Communication", duration: "4 years", fees: 60000, seats: 90 },
      { name: "M.E. Computer Science", duration: "2 years", fees: 55000, seats: 35 },
    ],
    reviews: [
      { rating: 4.3, comment: "Anna University is the gold standard for engineering in Tamil Nadu. Placements are solid.", author: "Karthikeyan Raja", batch: "2022", course: "B.E. CSE" },
      { rating: 4.2, comment: "Research facilities are excellent. Government college quality at affordable fees.", author: "Meenakshi Sundaram", batch: "2021", course: "B.E. ECE" },
    ],
  },
  {
    name: "Symbiosis Institute of Technology",
    location: "Pune, Maharashtra",
    city: "Pune",
    state: "Maharashtra",
    fees: 380000,
    rating: 4.0,
    placementsPercentage: 86,
    description:
      "SIT Pune is part of Symbiosis International University offering quality engineering programs in a vibrant educational ecosystem. Located in the IT hub of Pune with strong industry connections.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400",
    website: "https://www.sitpune.edu.in",
    phone: "+91-20-6122-6022",
    email: "info@sitpune.edu.in",
    established: 2008,
    totalStudents: 5000,
    accreditation: "NAAC A",
    type: "Deemed",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 380000, seats: 180 },
      { name: "B.Tech Artificial Intelligence", duration: "4 years", fees: 400000, seats: 60 },
      { name: "M.Tech IoT", duration: "2 years", fees: 320000, seats: 30 },
    ],
    reviews: [
      { rating: 4.0, comment: "Great college in Pune. Got internship in Infosys and full-time offer before graduation.", author: "Omkar Desai", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.1, comment: "Symbiosis provides a holistic education experience. Love the diverse campus life.", author: "Shreya Kulkarni", batch: "2021", course: "B.Tech AI" },
    ],
  },
  {
    name: "Pune Institute of Computer Technology",
    location: "Pune, Maharashtra",
    city: "Pune",
    state: "Maharashtra",
    fees: 120000,
    rating: 4.1,
    placementsPercentage: 88,
    description:
      "PICT is a prestigious private autonomous engineering college affiliated to Savitribai Phule Pune University. Known for producing excellent software engineers placed in top companies.",
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400",
    website: "https://www.pict.edu",
    phone: "+91-20-2437-0327",
    email: "director@pict.edu",
    established: 1983,
    totalStudents: 4000,
    accreditation: "NAAC A",
    type: "Private",
    courses: [
      { name: "B.E. Computer Engineering", duration: "4 years", fees: 120000, seats: 240 },
      { name: "B.E. Information Technology", duration: "4 years", fees: 115000, seats: 120 },
      { name: "M.E. Computer Engineering", duration: "2 years", fees: 100000, seats: 24 },
    ],
    reviews: [
      { rating: 4.2, comment: "PICT is the best private college in Pune for CS. Placements in Google, Amazon, FAANG!", author: "Siddharth Pawar", batch: "2022", course: "B.E. CE" },
      { rating: 4.0, comment: "Strong coding culture, excellent alumni, and very supportive professors.", author: "Gauri Joshi", batch: "2021", course: "B.E. IT" },
    ],
  },
  {
    name: "IIT Madras",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    fees: 200000,
    rating: 4.9,
    placementsPercentage: 99,
    description:
      "IIT Madras is consistently ranked #1 in India's NIRF rankings. A global research university with world-class facilities, exceptional faculty, and the highest placement package records in India.",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=400",
    website: "https://www.iitm.ac.in",
    phone: "+91-44-2257-8000",
    email: "dean.acad@iitm.ac.in",
    established: 1959,
    totalStudents: 9000,
    accreditation: "NAAC A++",
    type: "Government",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 200000, seats: 100 },
      { name: "B.Tech Aerospace Engineering", duration: "4 years", fees: 200000, seats: 40 },
      { name: "M.Tech AI", duration: "2 years", fees: 180000, seats: 40 },
      { name: "PhD Computer Science", duration: "4-5 years", fees: 50000, seats: 30 },
    ],
    reviews: [
      { rating: 5, comment: "IIT Madras is heaven for tech enthusiasts. Best research infrastructure in India.", author: "Sathyanarayanan K", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.8, comment: "Highest packages in India. My batch had students placed at 1.5 Cr CTC at top companies.", author: "Kavitha Narayan", batch: "2021", course: "M.Tech AI" },
    ],
  },
  {
    name: "Indian Institute of Management Ahmedabad",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    fees: 2300000,
    rating: 4.9,
    placementsPercentage: 100,
    description:
      "IIM Ahmedabad is the pinnacle of management education in India. Its graduates command the highest salaries and it is consistently ranked among the top business schools in Asia.",
    imageUrl: "https://images.unsplash.com/photo-1527576539890-dfa815648363?w=400",
    website: "https://www.iima.ac.in",
    phone: "+91-79-6632-4371",
    email: "pgp@iima.ac.in",
    established: 1961,
    totalStudents: 1200,
    accreditation: "AACSB",
    type: "Government",
    courses: [
      { name: "MBA (PGP)", duration: "2 years", fees: 2300000, seats: 385 },
      { name: "Executive MBA", duration: "1 year", fees: 3200000, seats: 70 },
      { name: "PhD Management", duration: "4 years", fees: 100000, seats: 20 },
    ],
    reviews: [
      { rating: 5, comment: "Best MBA in India, no question. The case method teaching is phenomenal.", author: "Vijay Agarwal", batch: "2022", course: "MBA PGP" },
      { rating: 4.9, comment: "Network from IIMA opens every door in corporate India. Placed at McKinsey!", author: "Radhika Menon", batch: "2021", course: "MBA PGP" },
    ],
  },
  {
    name: "Birla Institute of Technology Mesra",
    location: "Ranchi, Jharkhand",
    city: "Ranchi",
    state: "Jharkhand",
    fees: 300000,
    rating: 4.0,
    placementsPercentage: 85,
    description:
      "BIT Mesra is a renowned deemed university with a picturesque campus. Known for quality technical education and strong alumni network across the globe.",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=400",
    website: "https://bitmesra.ac.in",
    phone: "+91-651-227-5444",
    email: "vc@bitmesra.ac.in",
    established: 1955,
    totalStudents: 7500,
    accreditation: "NAAC A",
    type: "Deemed",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 300000, seats: 120 },
      { name: "B.E. Mechanical Engineering", duration: "4 years", fees: 290000, seats: 90 },
      { name: "M.E. Software Engineering", duration: "2 years", fees: 260000, seats: 30 },
    ],
    reviews: [
      { rating: 4.0, comment: "Beautiful campus in Ranchi. Great college life and decent placements.", author: "Rahul Tiwari", batch: "2022", course: "B.E. CSE" },
      { rating: 3.9, comment: "BIT Mesra has a strong alumni base. Tech culture and clubs are very active.", author: "Shruti Singh", batch: "2021", course: "B.E. Mech" },
    ],
  },
  {
    name: "IIIT Hyderabad",
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    fees: 300000,
    rating: 4.6,
    placementsPercentage: 96,
    description:
      "IIIT Hyderabad is a research-driven institution focused on computer science and information technology. Known for its research output and exceptional placements in top tech companies worldwide.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=400",
    website: "https://www.iiit.ac.in",
    phone: "+91-40-6653-1000",
    email: "info@iiit.ac.in",
    established: 1998,
    totalStudents: 2500,
    accreditation: "NAAC A++",
    type: "Deemed",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 300000, seats: 70 },
      { name: "B.Tech Electronics & Computer Science", duration: "4 years", fees: 300000, seats: 50 },
      { name: "M.Tech Computer Science", duration: "2 years", fees: 270000, seats: 40 },
    ],
    reviews: [
      { rating: 4.7, comment: "IIIT-H is where research meets industry. Got placed at Google Brain. Incredible!", author: "Samarth Reddy", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.5, comment: "World-class research labs and faculty who have worked at top global companies.", author: "Aishwarya Rao", batch: "2021", course: "M.Tech CSE" },
    ],
  },
  {
    name: "RV College of Engineering",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    fees: 190000,
    rating: 4.1,
    placementsPercentage: 87,
    description:
      "RVCE is a premier autonomous engineering college in Bangalore affiliated to VTU. Known for its strong placement record and exposure to the tech industry being located in Bangalore.",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=400",
    website: "https://www.rvce.edu.in",
    phone: "+91-80-2861-9152",
    email: "principal@rvce.edu.in",
    established: 1963,
    totalStudents: 6000,
    accreditation: "NAAC A+",
    type: "Private",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 190000, seats: 180 },
      { name: "B.E. Electronics", duration: "4 years", fees: 185000, seats: 120 },
      { name: "M.Tech Machine Learning", duration: "2 years", fees: 165000, seats: 25 },
    ],
    reviews: [
      { rating: 4.2, comment: "Being in Bangalore is a huge advantage. Lots of internships and startup connections.", author: "Tejas Hegde", batch: "2022", course: "B.E. CSE" },
      { rating: 4.0, comment: "RVCE is consistently one of the best private colleges in Karnataka. Great value.", author: "Nandita Sharma", batch: "2021", course: "B.E. Electronics" },
    ],
  },
  {
    name: "Netaji Subhas University of Technology",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    fees: 165000,
    rating: 4.2,
    placementsPercentage: 89,
    description:
      "NSUT (formerly NSIT) is a top government engineering university in Delhi known for producing excellent software engineers and tech professionals placed in India's best companies.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400",
    website: "https://www.nsut.ac.in",
    phone: "+91-11-2509-6000",
    email: "info@nsut.ac.in",
    established: 1983,
    totalStudents: 5000,
    accreditation: "NAAC A",
    type: "Government",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 165000, seats: 80 },
      { name: "B.Tech Information Technology", duration: "4 years", fees: 160000, seats: 80 },
      { name: "B.Tech Electronics", duration: "4 years", fees: 160000, seats: 60 },
    ],
    reviews: [
      { rating: 4.2, comment: "NSUT placements rival IITs in some cases. Got placed at Goldman Sachs!", author: "Yash Malhotra", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.3, comment: "Great alumni network and strong coding culture. Competitive programming is huge here.", author: "Nandani Goel", batch: "2021", course: "B.Tech IT" },
    ],
  },
  {
    name: "Kalinga Institute of Industrial Technology",
    location: "Bhubaneswar, Odisha",
    city: "Bhubaneswar",
    state: "Odisha",
    fees: 280000,
    rating: 3.9,
    placementsPercentage: 83,
    description:
      "KSOM is part of the KIIT Group offering management programs with focus on industry-readiness. Known for its modern campus and partnerships with leading companies.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400",
    website: "https://ksom.ac.in",
    phone: "+91-674-272-5113",
    email: "ksom@kiit.ac.in",
    established: 2005,
    totalStudents: 3000,
    accreditation: "NAAC A",
    type: "Deemed",
    courses: [
      { name: "MBA Marketing", duration: "2 years", fees: 280000, seats: 120 },
      { name: "MBA Finance", duration: "2 years", fees: 280000, seats: 120 },
      { name: "MBA HR", duration: "2 years", fees: 280000, seats: 60 },
    ],
    reviews: [
      { rating: 3.9, comment: "Good MBA program with industry exposure. Placements have improved each year.", author: "Biswa Pattanaik", batch: "2022", course: "MBA Marketing" },
      { rating: 3.8, comment: "KSOM's location in Bhubaneswar is growing as a business hub. Good prospects.", author: "Samita Das", batch: "2021", course: "MBA Finance" },
    ],
  },
  {
    name: "Christ University",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    fees: 280000,
    rating: 4.0,
    placementsPercentage: 84,
    description:
      "Christ University is a private deemed institution in Bangalore known for its arts, science, commerce, and management programs. Offers a strong holistic education with emphasis on values.",
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400",
    website: "https://christuniversity.in",
    phone: "+91-80-4012-9100",
    email: "registrar@christuniversity.in",
    established: 1969,
    totalStudents: 25000,
    accreditation: "NAAC A++",
    type: "Deemed",
    courses: [
      { name: "BCA Computer Applications", duration: "3 years", fees: 200000, seats: 200 },
      { name: "MBA", duration: "2 years", fees: 400000, seats: 150 },
      { name: "B.Com", duration: "3 years", fees: 150000, seats: 400 },
      { name: "B.Sc Data Science", duration: "3 years", fees: 220000, seats: 60 },
    ],
    reviews: [
      { rating: 4.1, comment: "Christ Uni has a vibrant campus culture. Discipline is strict but it builds character.", author: "Anita Mathew", batch: "2022", course: "BCA" },
      { rating: 3.9, comment: "Good for MBA. The faculty here has excellent industry experience.", author: "George Philip", batch: "2021", course: "MBA" },
    ],
  },
  {
    name: "Visvesvaraya Technological University",
    location: "Belgaum, Karnataka",
    city: "Belgaum",
    state: "Karnataka",
    fees: 80000,
    rating: 3.7,
    placementsPercentage: 78,
    description:
      "VTU is one of the largest technical universities in Asia affiliating 200+ engineering colleges across Karnataka. The main campus offers quality education at affordable government rates.",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=400",
    website: "https://vtu.ac.in",
    phone: "+91-831-249-8200",
    email: "vc@vtu.ac.in",
    established: 1998,
    totalStudents: 4000,
    accreditation: "NAAC A",
    type: "Government",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 80000, seats: 60 },
      { name: "B.E. Civil Engineering", duration: "4 years", fees: 75000, seats: 60 },
      { name: "M.Tech Computer Science", duration: "2 years", fees: 65000, seats: 18 },
    ],
    reviews: [
      { rating: 3.7, comment: "Government university with solid fundamentals. Fees are very affordable.", author: "Mahesh Hiremath", batch: "2022", course: "B.E. CSE" },
      { rating: 3.8, comment: "VTU has improved placements over the years. The affiliated colleges vary a lot.", author: "Kavya Patil", batch: "2021", course: "B.E. Civil" },
    ],
  },
  {
    name: "IIT Kharagpur",
    location: "Kharagpur, West Bengal",
    city: "Kharagpur",
    state: "West Bengal",
    fees: 225000,
    rating: 4.7,
    placementsPercentage: 97,
    description:
      "IIT Kharagpur is the oldest IIT and one of the finest technical institutes in Asia. Home to numerous research centers and known for its vast campus and diverse academic offerings.",
    imageUrl: "https://images.unsplash.com/photo-1527576539890-dfa815648363?w=400",
    website: "https://www.iitkgp.ac.in",
    phone: "+91-3222-255-221",
    email: "registrar@adm.iitkgp.ac.in",
    established: 1951,
    totalStudents: 12000,
    accreditation: "NAAC A++",
    type: "Government",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 225000, seats: 120 },
      { name: "B.Tech Aerospace Engineering", duration: "4 years", fees: 225000, seats: 40 },
      { name: "Integrated M.Sc Mathematics", duration: "5 years", fees: 225000, seats: 30 },
      { name: "MBA", duration: "2 years", fees: 300000, seats: 120 },
    ],
    reviews: [
      { rating: 4.7, comment: "IIT KGP's campus is absolutely massive. The research and academic culture are unmatched.", author: "Soumya Chatterjee", batch: "2022", course: "B.Tech CSE" },
      { rating: 4.6, comment: "Best campus life among all IITs. Technology Student Gymkhana events are legendary.", author: "Payal Banerjee", batch: "2021", course: "B.Tech Aerospace" },
    ],
  },
  {
    name: "Graphic Era University",
    location: "Dehradun, Uttarakhand",
    city: "Dehradun",
    state: "Uttarakhand",
    fees: 220000,
    rating: 3.8,
    placementsPercentage: 80,
    description:
      "Graphic Era University is a private institution offering programs in engineering, management, and applied sciences. Located in the scenic city of Dehradun with a focus on practical learning.",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=400",
    website: "https://www.geu.ac.in",
    phone: "+91-135-269-5000",
    email: "info@geu.ac.in",
    established: 1993,
    totalStudents: 10000,
    accreditation: "NAAC A",
    type: "Deemed",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 220000, seats: 200 },
      { name: "B.Tech Mechanical", duration: "4 years", fees: 210000, seats: 100 },
      { name: "MBA", duration: "2 years", fees: 300000, seats: 80 },
    ],
    reviews: [
      { rating: 3.8, comment: "Nice campus in Dehradun. Good for students from Uttarakhand region.", author: "Ankur Nautiyal", batch: "2022", course: "B.Tech CSE" },
      { rating: 3.7, comment: "Placements have improved significantly. Core companies visit regularly now.", author: "Pallavi Bhatt", batch: "2021", course: "MBA" },
    ],
  },
  {
    name: "Hindustan Institute of Technology",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    fees: 180000,
    rating: 3.7,
    placementsPercentage: 79,
    description:
      "Hindustan Institute of Technology and Science is a private deemed university in Chennai offering programs in engineering, architecture, and management with focus on applied research.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=400",
    website: "https://hindustanuniv.ac.in",
    phone: "+91-44-2274-1810",
    email: "registrar@hindustanuniv.ac.in",
    established: 1985,
    totalStudents: 12000,
    accreditation: "NAAC A",
    type: "Deemed",
    courses: [
      { name: "B.Tech Aerospace Engineering", duration: "4 years", fees: 200000, seats: 60 },
      { name: "B.Tech Computer Science", duration: "4 years", fees: 180000, seats: 200 },
      { name: "B.Arch", duration: "5 years", fees: 190000, seats: 40 },
    ],
    reviews: [
      { rating: 3.7, comment: "Aerospace program is the standout at Hindustan Uni. Good labs and faculty.", author: "Vikram Rajendran", batch: "2022", course: "B.Tech Aerospace" },
      { rating: 3.8, comment: "Average placements but the education quality is decent for the fees charged.", author: "Lakshmi Priya", batch: "2021", course: "B.Tech CSE" },
    ],
  },
  {
    name: "NMIMS University",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    fees: 750000,
    rating: 4.2,
    placementsPercentage: 93,
    description:
      "NMIMS is a private deemed university known for its outstanding MBA program. The Mukesh Patel School of Technology and Management is one of the best management colleges in India.",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=400",
    website: "https://www.nmims.edu",
    phone: "+91-22-4235-5555",
    email: "admissions@nmims.edu",
    established: 1981,
    totalStudents: 15000,
    accreditation: "NAAC A+",
    type: "Deemed",
    courses: [
      { name: "MBA", duration: "2 years", fees: 750000, seats: 240 },
      { name: "B.Tech Computer Science", duration: "4 years", fees: 500000, seats: 120 },
      { name: "B.Pharm", duration: "4 years", fees: 400000, seats: 60 },
    ],
    reviews: [
      { rating: 4.3, comment: "NMIMS MBA is fantastic. Got placed at Deloitte with excellent package!", author: "Mihir Shah", batch: "2022", course: "MBA" },
      { rating: 4.1, comment: "Mumbai location, great faculty, and amazing industry exposure. Worth the fees.", author: "Riya Mehta", batch: "2021", course: "B.Tech CSE" },
    ],
  },
  {
    name: "Osmania University",
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    fees: 45000,
    rating: 3.9,
    placementsPercentage: 80,
    description:
      "Osmania University is one of India's oldest and largest universities established in 1918. It offers programs across science, arts, commerce, engineering, and law at very affordable government fees.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400",
    website: "https://www.osmania.ac.in",
    phone: "+91-40-2768-2363",
    email: "registrar@osmania.ac.in",
    established: 1918,
    totalStudents: 30000,
    accreditation: "NAAC A",
    type: "Government",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 45000, seats: 120 },
      { name: "B.Com", duration: "3 years", fees: 25000, seats: 200 },
      { name: "M.Sc Computer Science", duration: "2 years", fees: 35000, seats: 40 },
    ],
    reviews: [
      { rating: 4.0, comment: "Historic institution with excellent faculty. A pride of Hyderabad!", author: "Mohammed Irfan", batch: "2022", course: "B.E. CSE" },
      { rating: 3.8, comment: "Government fees are very affordable. Campus is beautiful with heritage buildings.", author: "Shalini Reddy", batch: "2021", course: "B.Com" },
    ],
  },
];

async function main() {
  console.log("🌱 Starting database seeding...");

  // Clear existing data
  await prisma.savedCollege.deleteMany();
  await prisma.review.deleteMany();
  await prisma.course.deleteMany();
  await prisma.college.deleteMany();
  await prisma.user.deleteMany();

  console.log("🗑️  Cleared existing data");

  // Seed colleges
  for (const collegeData of colleges) {
    const { courses, reviews, ...college } = collegeData;
    
    const createdCollege = await prisma.college.create({
      data: {
        ...college,
        courses: {
          create: courses,
        },
        reviews: {
          create: reviews,
        },
      },
    });
    
    console.log(`✅ Created: ${createdCollege.name}`);
  }

  // Create a demo user
  const hashedPassword = await bcrypt.hash("password123", 10);
  
  await prisma.user.create({
    data: {
      email: "demo@college.com",
      name: "Demo User",
      password: hashedPassword,
    },
  });

  console.log("👤 Created demo user: demo@college.com / password123");
  console.log(`\n🎉 Seeding complete! ${colleges.length} colleges added.`);
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
